// src/pages/Script/Code/Version.vue
<template>
  <q-card-section>
    <q-card
      flat
      v-for="(item, index) in version"
      :key="index"
      class="version-item"
    >
      <q-card-section>
        <div class="text-h5">
          v{{ item.version }}
          <q-chip
            v-if="index == 0"
            outline
            color="green"
            text-color="green"
            size="sm"
          >
            最新
          </q-chip>
          <span class="text-caption" style="float: right">{{
            dateformat(item.createtime * 1000)
          }}</span>
        </div>
      </q-card-section>
      <q-separator />
      <q-card-section>
        <div v-if="!item.changelog">作者偷懒没有写更新日志</div>
        <div v-else>
          <MarkdownView :id="item.version" :content="item.changelog" />
        </div>
      </q-card-section>
      <q-separator />
      <q-card-actions align="right">
        <q-btn-group flat>
          <q-btn
            class="text-caption"
            type="a"
            :href="
              '/scripts/code/' +
              id +
              '/' +
              encodeURIComponent(script.name) +
              '.user.js?version=' +
              item.version
            "
            color="primary"
            label="安装此版本"
          />
          <q-btn
            outline
            class="text-caption"
            type="a"
            target="_blank"
            href="https://bbs.tampermonkey.net.cn/thread-57-1-1.html"
            color="primary"
            label="如何安装?"
          />
        </q-btn-group>
      </q-card-actions>
    </q-card>
  </q-card-section>
</template>

<script lang="ts">
import { Cookies, useMeta } from 'quasar';
import { defineComponent } from 'vue';
import { RouteLocationNormalizedLoaded } from 'vue-router';
import MarkdownView from '@Components/MarkdownView.vue';
import { formatDate } from '@App/utils/utils';

export default defineComponent({
  components: { MarkdownView },
  preFetch({ store, currentRoute, ssrContext }) {
    if (!ssrContext) {
      return;
    }
    const cookies = process.env.SERVER ? Cookies.parseSSR(ssrContext) : Cookies;
    return store.dispatch('scripts/fetchVersionList', {
      id: currentRoute.params.id,
      page: parseInt(<string>currentRoute.query.page || '1'),
      count: 20,
      cookies: cookies,
    });
  },
  setup() {
    useMeta({ title: '版本列表' });
  },
  computed: {
    id() {
      return parseInt(<string>this.$route.params.id);
    },
    script() {
      return this.$store.state.scripts.script;
    },
    version() {
      return this.$store.state.scripts.version;
    },
    total() {
      return this.$store.state.scripts.total;
    },
  },
  unmounted() {
    void this.$store.commit('scripts/resetPreFetch');
  },
  mounted() {
    if (!this.$store.state.scripts.preFetch) {
      void this.reload(this.$route);
    }
    // else {
    //   this.version = this.$store.state.scripts.version;
    // }
  },
  methods: {
    async reload(currentRoute: RouteLocationNormalizedLoaded) {
      await this.$store.dispatch('scripts/fetchVersionList', {
        id: currentRoute.params.id,
        page: parseInt(<string>currentRoute.query.page || '1'),
        count: 20,
      });
      console.log(this.$store.state.scripts.preFetch);
    },
  },
  data() {
    return {
      dateformat: formatDate,
    };
  },
});
</script>

<style scoped>
.version-item:not(:first-child) {
  margin-top: 30px;
}
</style>

// app/routes/script-show-page/$id/version.tsx
import {
  DiffOutlined,
  DownloadOutlined,
  QuestionCircleOutlined,
} from '@ant-design/icons';
import type { LoaderFunction } from '@remix-run/node';
import { json } from '@remix-run/node';
import { useLoaderData, useNavigate } from '@remix-run/react';
import { Button, Card, List, Space, Tag, Tooltip } from 'antd';
import { useContext, useState } from 'react';
import { formatDate } from '~/utils/utils';
import MarkdownView from '~/components/MarkdownView';
import { ScriptContext } from '~/context-manager';
import { ScriptVersionList } from '~/services/scripts/api';
import type { ScriptCode } from '~/services/scripts/types';

type LoaderData = {
  list: ScriptCode[];
  total: number;
};

export const loader: LoaderFunction = async ({ params }) => {
  const resp = await ScriptVersionList(parseInt(params.id as string));
  return json({
    list: resp.list,
    total: resp.total,
  } as LoaderData);
};
export default function Version() {
  const data = useLoaderData<LoaderData>();
  const navigate = useNavigate();
  const [diff, setDiff] = useState(-1);
  const script = useContext(ScriptContext);
  return (
    <Card>
      <List
        dataSource={data.list}
        renderItem={(item, index) => (
          <Card className={index != 0 ? '!mt-3' : ''}>
            <Card.Grid
              hoverable={false}
              style={{
                padding: '8px 8px',
                width: '100%',
              }}
              className="script-info-item"
            >
              <div className="flex flex-col">
                <div className="flex flex-row justify-between">
                  <Space>
                    <span className="text-2xl">{item.version}</span>
                    {index == 0 && <Tag color="green">最新</Tag>}
                  </Space>
                  <span className="text-xs">{formatDate(item.createtime)}</span>
                </div>
                <div className="py-2">
                  <MarkdownView
                    id={'version-' + item.id}
                    content={item.changelog || '作者偷懒没有写更新日志'}
                  />
                </div>
              </div>
            </Card.Grid>
            <Card.Grid
              hoverable={false}
              style={{
                padding: '8px 8px',
                width: '100%',
                textAlign: 'right',
              }}
              className="script-info-item"
            >
              <div>
                <Button.Group size="small">
                  <Button
                    className="!rounded-none"
                    type="primary"
                    href={
                      '/scripts/code/' +
                      script.script?.id +
                      '/' +
                      script.script?.name +
                      '.user.js?version=' +
                      item.version
                    }
                    icon={<DownloadOutlined />}
                  >
                    安装{item.version}
                  </Button>

                  <Tooltip placement="bottom" title="如何安装?">
                    <Button
                      className="!rounded-none"
                      type="primary"
                      icon={<QuestionCircleOutlined />}
                      color="#3874cb"
                      href="https://bbs.tampermonkey.net.cn/thread-57-1-1.html"
                      target="_blank"
                    ></Button>
                  </Tooltip>

                  <Tooltip placement="bottom" title="选择两个版本,对比代码变化">
                    <Button
                      className="!rounded-none"
                      icon={<DiffOutlined />}
                      danger={diff == index}
                      onClick={() => {
                        if (diff == index) {
                          setDiff(-1);
                        }
                        if (diff != -1) {
                          navigate({
                            pathname:
                              '/script-show-page/' +
                              script.script?.id +
                              '/diff',
                            search:
                              '?version1=' +
                              data.list[diff].version +
                              '&version2=' +
                              item.version,
                          });
                          return;
                        }
                        setDiff(index);
                      }}
                    ></Button>
                  </Tooltip>
                </Button.Group>
              </div>
            </Card.Grid>
          </Card>
        )}
      ></List>
    </Card>
  );
}
